// ── Centralized Permissions & Roles ──

export const ROLES = {
  VIEWER: 'VIEWER',
  TRADER: 'TRADER',
  ANALYST: 'ANALYST',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  TRADE_EXECUTE: 'trade:execute',
  TRADE_CANCEL: 'trade:cancel',
  TRADE_READ: 'trade:read',
  EXCHANGE_CONNECT: 'exchange:connect',
  EXCHANGE_READ: 'exchange:read',
  RISK_VIEW: 'risk:view',
  RISK_MANAGE: 'risk:manage',
  SCORING_MANAGE: 'scoring:manage',
  AI_READ: 'ai:read',
  DATASOURCE_READ: 'datasource:read',
  AUDIT_READ: 'audit:read',
  AUDIT_EXPORT: 'audit:export',
  ADMIN_USER_MANAGE: 'admin:user:manage',
  ADMIN_SYSTEM: 'admin:system',
  USER_READ: 'user:read',
  BACKTEST_RUN: 'backtest:run',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.TRADE_EXECUTE, PERMISSIONS.TRADE_CANCEL, PERMISSIONS.TRADE_READ,
    PERMISSIONS.EXCHANGE_CONNECT, PERMISSIONS.EXCHANGE_READ,
    PERMISSIONS.RISK_VIEW, PERMISSIONS.USER_READ,
    PERMISSIONS.AUDIT_READ, PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.AI_READ, PERMISSIONS.DATASOURCE_READ,
    PERMISSIONS.ADMIN_USER_MANAGE, PERMISSIONS.ADMIN_SYSTEM,
    PERMISSIONS.BACKTEST_RUN,
  ],
  TRADER: [
    PERMISSIONS.TRADE_EXECUTE, PERMISSIONS.TRADE_CANCEL, PERMISSIONS.TRADE_READ,
    PERMISSIONS.EXCHANGE_CONNECT, PERMISSIONS.EXCHANGE_READ,
    PERMISSIONS.RISK_VIEW, PERMISSIONS.DATASOURCE_READ,
  ],
  ANALYST: [
    PERMISSIONS.TRADE_READ, PERMISSIONS.EXCHANGE_READ,
    PERMISSIONS.AI_READ, PERMISSIONS.DATASOURCE_READ,
    PERMISSIONS.AUDIT_READ, PERMISSIONS.RISK_VIEW,
    PERMISSIONS.SCORING_MANAGE,
    PERMISSIONS.BACKTEST_RUN,
  ],
  VIEWER: [PERMISSIONS.TRADE_READ, PERMISSIONS.EXCHANGE_READ],
};
