-- CreateTable
CREATE TABLE `BacktestReport` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `symbol` VARCHAR(191) NOT NULL,
    `startDate` DATETIME(3) NOT NULL,
    `endDate` DATETIME(3) NOT NULL,
    `initialCapital` DOUBLE NOT NULL,
    `finalCapital` DOUBLE NOT NULL,
    `totalReturn` DOUBLE NOT NULL,
    `totalPnL` DOUBLE NOT NULL,
    `totalTrades` INTEGER NOT NULL,
    `winningTrades` INTEGER NOT NULL,
    `losingTrades` INTEGER NOT NULL,
    `winRate` DOUBLE NOT NULL,
    `avgWin` DOUBLE NOT NULL,
    `avgLoss` DOUBLE NOT NULL,
    `profitFactor` DOUBLE NOT NULL,
    `maxDrawdown` DOUBLE NOT NULL,
    `maxDrawdownDuration` INTEGER NOT NULL,
    `sharpeRatio` DOUBLE NOT NULL,
    `sortinoRatio` DOUBLE NOT NULL,
    `calmarRatio` DOUBLE NOT NULL,
    `totalFees` DOUBLE NOT NULL,
    `equityCurve` LONGTEXT NOT NULL,
    `drawdownCurve` LONGTEXT NOT NULL,
    `monthlyReturns` LONGTEXT NOT NULL,
    `trades` LONGTEXT NOT NULL,
    `parameters` LONGTEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `BacktestReport_userId_idx`(`userId`),
    INDEX `BacktestReport_symbol_idx`(`symbol`),
    INDEX `BacktestReport_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
